### PR TITLE
finished US02_Atittaya

### PR DESCRIPTION
**Pull request by Fangzaya**
Hi guys, please review my code and merge if everything looks goods, 
Thanks!!

### CODE REVIEW

**Review by KhrystynaN — COMMENTED** [review]
Everything looks good for me, Attitaya. I'm only not sure about "s02_AT_Step_Definitions extends BasePage". Should we extend BasePage in StepDef? I think it's already done in Pages. Please let me know what do think. Thank you

**Comment by Fangzaya** [comment]
@KhrystynaN oh yes! I forgot to delete it! thank  you :)

**Comment by Fangzaya** [comment]
@KhrystynaN 
I just edit and push , Do I need to create a PR again or we can merge from this one ?

**Review by KhrystynaN — APPROVED** [review]
All good, Thank you

**Pull request merged**
